language: objective-c
# Whitelisting example
branches:
only:
- master

env:
  global:
#  - ALL_NOTES=""
#  - 'DEVELOPER_NAME="iPhone Distribution: V2 Solutions (JTKBCAGUVC)"'
#  - PROFILE_NAME="AppNavigation_Ad_Hoc"
  - INFOPLIST_FILE="./AppNavigation/Info.plist"
#  - APP_WORKSPACE_PATH="TravisNavigation/AppNavigation.xcworkspace"
  - secure: bJ1sFGf/q3CxKbYcVwOti+TVwokrcgJ5PVfDpgugeAEPNyweBux4cWI6YvLp1WJIO0velz9WjWwKcQLHIb+wDF9uzoT1OHeMjTsMSEYxm+pGdQmOvZHbfFFw3Jaw3KqjIefRK+SCRMgfS2uwxLNzuz7N8immstVNLIeYFZ6AUYY=
  - secure: Yn47yJidwCJefFnfS9urATW1LUHV6ErvApOyp5Qbhg4xnhZjQyibjln50/3e/sZBSp8gtCfx9QkUwLoBWxTTX4W4CmdvWK04EMc7qq0n9Xk2TdfR/+26YldI9Sx6aAWpaSYCvJ8EnJ47U5tjHo17CIHiijwyWJGYBA8xZ3B604k=
  - secure: jtwbKzVZMluFd60R9v2mbi91kn0muHObiYvVqQZxjDN9VJ5FdM0J3W2k9d0EIBwfkcvzVPLApXlJfE9M34Y/CuXs/mBh2OxMXbUSx46AR4BE8Z9q2XFOt/de9B5O3JGs1JCiCMlbESSpyGJdLBjvb+ixOwmNtmux2NykZPw+lvA=
  - secure: FgT/A59Qckv18O35eeiBl2F54OpISOQGOcppLQ2pFDNqiTuOlnX2acGYJcigR2TWQvjQJ9xGYB4AecLQEtCNyDYEL/7IyI/AMtGrX3o1JrxVwo9ZTEhD9sBFHuT0n/g2DPiVb/jxwJItg7yQNOocsILcROiF2oHmV1G4phRCKe4=
  - PROJECT_ID=1114232
  - TOKEN='cf9391f2af5a2b68da2755a27bce2bff'
  - OUTPUT_FILE_NAME='jsonrespone.text'
  - ALL_COMMENTS='allcomments.text'

before_install:
- chmod +x config.sh

- chmod +x scripts/download_jq_framwork.sh
- chmod +x scripts/Get_All_Pivotal_Comments.sh

- chmod +x scripts/add-key.sh
- chmod +x scripts/remove-key.sh
- chmod +x scripts/update-bundle.sh
- chmod +x scripts/sign-and-upload.sh
before_script:
- . ./config.sh
- ./scripts/download_jq_framwork.sh
- echo $APP_NAME

- echo "Testing Branches Nitesh"

- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/AppNavigation_Ad_Hoc.mobileprovision.enc
  -d -a -out scripts/profile/AppNavigation_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
#- xcodebuild test -workspace AppNavigation.xcworkspace -scheme AppNavigation -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#- xcodebuild -workspace AppNavigation.xcworkspace -scheme AppNavigation -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace AppNavigation.xcworkspace -scheme AppNavigation -sdk iphoneos
  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/Get_All_Pivotal_Comments.sh
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
