language: objective-c
# Whitelisting example
branches:
only:
- master



before_install:
#- chmod +x ./scripts/jq
#- sudo cp ./scripts/jq /usr/local/bin

- chmod +x scripts/download_jq_framwork.sh
- chmod +x scripts/Get_All_Pivotal_Comments.sh


before_script:

- ./scripts/Get_All_Pivotal_Comments.sh

script:

after_success:

after_script:

